### PR TITLE
add new job ad

### PR DESCRIPTION
**Pull request by gecofernando**
Added Android developer job ad.
Minor fixes for FB and Twitter sharing meta-tags.
Minor fixes in 'Jobs' tab.

### CODE REVIEW

**Comment by adamantivm** [comment]
@gecofernando the images in the job ad seem too big. I can't tell for sure but they seem maybe like 700k each? Could you please scale them and compress them? They should be in the order of magnitude of 20k or so each.

**Comment by gecofernando** [comment]
Sorry, my bad!
Will fix it now.

**Comment by gecofernando** [comment]
I think it's done. Something weird happened with my PR, but it should be
there.

**Comment by adamantivm** [comment]
:+1:

**Pull request merged**
